[[main]]
identifier = "pro"
name = "Pro"
url = "/pro/"
weight = 1

[[main]]
identifier = "personal"
name = "Personal"
url = "/personal/"
weight = 2

[[main]]
identifier = "publications"
name = "Publications"
url = "/pro/publications/"
weight = 3

[[main]]
identifier = "teaching"
name = "Teaching"
url = "/pro/teaching/"
weight = 4

[[main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 5

# Icons can be found & downloaded here : https://tablericons.com/

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/jonasmehtali/"
weight = 1

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://www.youtube.com/@JonasMht"
weight = 2

[[social]]
identifier = "cv"
name = "My CV"
url = "/pro/about/jonas-mehtali-resume.pdf"
weight = 3

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/JonasMht"
weight = 4
