# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true


# Icons can be found & downloaded here : https://tablericons.com/

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/jonasmehtali/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://www.youtube.com/@JonasMht"

[social.params]
icon = "brand-youtube"


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/JonasMht"

[social.params]
icon = "brand-github"
